-- local jdtls_exec = vim.fn.stdpath 'data' .. '/mason/bin/jdtls'
-- local java_dap_dir = vim.fn.stdpath 'data' .. '/mason/share' .. '/java-debug-adapter'
--
-- local config = {
--   cmd = { jdtls_exec },
--
--   init_options = {
--     bundles = { java_dap_dir .. '/com.microsoft.java.debug.plugin.jar' },
--   },
-- }
-- require('jdtls').start_or_attach(config)
